# Generated by Django 4.2.23 on 2025-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_barcode_alter_product_category_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="performance_metrics",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
    ]
