# Generated by Django 4.2.23 on 2025-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_barcode_alter_product_category_and_more"),
        ("warehouses", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[("ADD", "Add"), ("REMOVE", "Remove"), ("CORRECT", "Correct")],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("product", "location")},
        ),
    ]
