# Generated by Django 4.2.23 on 2025-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_barcode_alter_product_category_and_more"),
        ("warehouses", "0002_alter_location_name_alter_location_type_and_more"),
        ("inventory", "0002_alter_stockadjustment_adjustment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouses.location",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="adjustment_type",
            field=models.CharField(
                blank=True,
                choices=[("ADD", "Add"), ("REMOVE", "Remove"), ("CORRECT", "Correct")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
